#!usr/bin/env python3
#-*- coding:utf-8 -*-
#Başlangıç 22.11.2023 20:20
#Bitiş -:-
import os
os.system("clear")
os.system("pkg install figlet")
os.system('clear')
os.system ("figlet KanliSilah")
print("#Codded by Hacker KanlıSilah and Hacker Banu")
print("\nHoş gəldiniz HACKER BANU sizin üçün nə edə bilərəm. \n \n 1. Bütün paketləri yüklə \n 2. Hack alətlərini yüklə ")
a = input(str("\nSeçiminiz:"))
if a == "1":
    print("Lazımlı paketlər yüklənir. Xaiş olunur gözləyin, bu sizin internet bağlantınızın surətindən asılı olaraq vaxt apara bilər")
    print("8")
    os.system("sleep 1")
    print("7")
    os.system("sleep 1")
    print("6")
    os.system("sleep 1")
    print("5")
    os.system("sleep 1")
    print("4")
    os.system("sleep 1")
    print("3")
    os.system("sleep 1")
    print("2")
    os.system("sleep 1")
    print("1")
    print("Diqqət yükləmə başlayır")
    os.system("pkg install git -y")
    os.system("pkg install python -y")
    os.system("pkg install python2 -y")
    os.system("pkg install python3 -y")
    os.system("pkg install bash -y")
    os.system("pkg install curl -y ")
    os.system("pkg install php -y")
    os.system("pkg install perl -y")
    os.system("pkg install busybox -y")
    os.system("pkg install cmatrix -y")
    os.system("pkg install dnsutils -y")
    os.system("pkg install hashdeep -y")
    os.system("pkg install hexcurse -y")
    os.system("pkg install json-c -y")
    os.system("pkg install openssl -y")
    os.system("pkg install sslscan -y")
    os.system("pkg install unzip -y")
    os.system("pkg install nmap -y")
    os.system("pkg install termux-tools -y")
    os.system("pkg install wget -y")
    os.system("pkg install root-repo")
    os.system("pkg install x11-repo")
    os.system("pkg install tur-repo")
    os.system("apt update -y")
    os.system("apt upgrade -y")
    os.system("pkg update -y && pkg upgrade -y")
else:
    print(" Bu Özəllik hal-hazırda mövcud deyil. Gələcək güncəllənmələri gözləyin.")
    os.system("python XalaqiziV2.py")
